# Analysis Options for AI-Generated Code Maintainability
# Run: flutter analyze / dart analyze

include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

  # 型安全性の強化
  language:
    strict-casts: true
    strict-raw-types: true

  errors:
    unused_import: error
    unused_local_variable: warning
    dead_code: warning
    # Disable non_nullable_equals_parameter for Freezed generated files
    non_nullable_equals_parameter: ignore
    invalid_annotation_target: ignore
    # Disable asset_does_not_exist for .env file (not included in repository)
    asset_does_not_exist: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "build/**"
    - ".dart_tool/**"
    - "test/**"
    # Exclude backup directory from all lint checks
    - "lib/backup/**"

linter:
  rules:
    # 未使用コード検出（analyzerのerrorsセクションで設定済み）
    - unnecessary_late

    # イミュータビリティ（変更に強い）
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables

    # 型安全性
    - avoid_dynamic_calls
    - avoid_types_as_parameter_names
    - prefer_typing_uninitialized_variables
    - always_declare_return_types
    - type_annotate_public_apis

    # null安全
    - avoid_null_checks_in_equality_operators
    - null_check_on_nullable_type_parameter
    - avoid_returning_null_for_future

    # コード構造・可読性
    - directives_ordering
    - sort_child_properties_last
    - require_trailing_commas
    - prefer_single_quotes
    - prefer_relative_imports
    - sort_pub_dependencies

    # エラー防止
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - no_duplicate_case_values
    - avoid_empty_else
    - avoid_returning_null_for_void
    - empty_catches

    # Flutter固有
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
