// Mocks generated by Mockito 5.4.5 from annotations
// in goal_timer/test/features/statistics/presentation/screens/statistics_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:goal_timer/features/statistics/domain/entities/daily_stats.dart'
    as _i3;
import 'package:goal_timer/features/statistics/domain/entities/statistics.dart'
    as _i6;
import 'package:goal_timer/features/statistics/domain/repositories/statistics_repository.dart'
    as _i2;
import 'package:goal_timer/features/statistics/domain/usecases/get_daily_stats_usecase.dart'
    as _i7;
import 'package:goal_timer/features/statistics/domain/usecases/get_statistics_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStatisticsRepository_0 extends _i1.SmartFake
    implements _i2.StatisticsRepository {
  _FakeStatisticsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDailyStats_1 extends _i1.SmartFake implements _i3.DailyStats {
  _FakeDailyStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetStatisticsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStatisticsUseCase extends _i1.Mock
    implements _i4.GetStatisticsUseCase {
  MockGetStatisticsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StatisticsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeStatisticsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.StatisticsRepository);

  @override
  _i5.Future<List<_i6.Statistics>> execute({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i5.Future<List<_i6.Statistics>>.value(<_i6.Statistics>[]),
      ) as _i5.Future<List<_i6.Statistics>>);
}

/// A class which mocks [GetDailyStatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDailyStatsUseCase extends _i1.Mock
    implements _i7.GetDailyStatsUseCase {
  MockGetDailyStatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StatisticsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeStatisticsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.StatisticsRepository);

  @override
  _i5.Future<_i3.DailyStats> execute(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [date],
        ),
        returnValue: _i5.Future<_i3.DailyStats>.value(_FakeDailyStats_1(
          this,
          Invocation.method(
            #execute,
            [date],
          ),
        )),
      ) as _i5.Future<_i3.DailyStats>);
}
