// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_Vvrt89kHciKgGHWG83cp77Y2troe2k',
    appId: '1:817605522713:android:8c470807928f452f9a4188',
    messagingSenderId: '817605522713',
    projectId: 'goal-timer-43a41',
    storageBucket: 'goal-timer-43a41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDujLVNqo7VsJ7h52JaiENPskL-lxJ60jo',
    appId: '1:817605522713:ios:d747a1806892cb069a4188',
    messagingSenderId: '817605522713',
    projectId: 'goal-timer-43a41',
    storageBucket: 'goal-timer-43a41.firebasestorage.app',
    androidClientId: '817605522713-037cipbqtfbj2k9aslf37354th773o4k.apps.googleusercontent.com',
    iosClientId: '817605522713-inj03mbi20bsc85lp2mvpq9kh497d180.apps.googleusercontent.com',
    iosBundleId: 'com.goal.timer',
  );
}
