// Mocks generated by Mockito 5.4.5 from annotations
// in goal_timer/test/features/settings/presentation/screens/settings_screen_account_linking_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i6;
import 'package:goal_timer/core/services/data_migration_service.dart' as _i8;
import 'package:goal_timer/core/services/temp_user_service.dart' as _i2;
import 'package:goal_timer/features/auth/domain/entities/auth_state.dart'
    as _i7;
import 'package:goal_timer/features/auth/presentation/view_models/auth_view_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:state_notifier/state_notifier.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TempUserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTempUserService extends _i1.Mock implements _i2.TempUserService {
  MockTempUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> generateTempUserId() => (super.noSuchMethod(
        Invocation.method(
          #generateTempUserId,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #generateTempUserId,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String?> getTempUserId() => (super.noSuchMethod(
        Invocation.method(
          #getTempUserId,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<bool> isTempUserExpired() => (super.noSuchMethod(
        Invocation.method(
          #isTempUserExpired,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteTempUserData() => (super.noSuchMethod(
        Invocation.method(
          #deleteTempUserData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateOnboardingStep(int? step) => (super.noSuchMethod(
        Invocation.method(
          #updateOnboardingStep,
          [step],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getOnboardingStep() => (super.noSuchMethod(
        Invocation.method(
          #getOnboardingStep,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> hasTempUser() => (super.noSuchMethod(
        Invocation.method(
          #hasTempUser,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int?> getTempUserCreatedAt() => (super.noSuchMethod(
        Invocation.method(
          #getTempUserCreatedAt,
          [],
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);

  @override
  bool validateTempUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #validateTempUserId,
          [userId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AuthViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthViewModel extends _i1.Mock implements _i5.AuthViewModel {
  MockAuthViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i6.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i3.Stream<_i7.AuthState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i7.AuthState>.empty(),
      ) as _i3.Stream<_i7.AuthState>);

  @override
  _i7.AuthState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i7.AuthState.initial,
      ) as _i7.AuthState);

  @override
  set state(_i7.AuthState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.AuthState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _i7.AuthState.initial,
      ) as _i7.AuthState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signUpWithEmail(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [
            email,
            password,
            displayName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signInWithGoogleAndMigrate({
    _i2.TempUserService? tempUserService,
    _i8.DataMigrationService? migrationService,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogleAndMigrate,
          [],
          {
            #tempUserService: tempUserService,
            #migrationService: migrationService,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signInWithAppleAndMigrate({
    _i2.TempUserService? tempUserService,
    _i8.DataMigrationService? migrationService,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithAppleAndMigrate,
          [],
          {
            #tempUserService: tempUserService,
            #migrationService: migrationService,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void setGuestState() => super.noSuchMethod(
        Invocation.method(
          #setGuestState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetToInitial() => super.noSuchMethod(
        Invocation.method(
          #resetToInitial,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i7.AuthState? old,
    _i7.AuthState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.RemoveListener addListener(
    _i9.Listener<_i7.AuthState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i6.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
